config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admins' => 'admins#index'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :users
  resources :products
  resources :posts
  resources :subscriptions
  resources :inquiries
  root 'main#home'
  get '/home', to: 'main#home'
  get '/catalog', to: 'main#catalog'
  get 'services', to: 'main#services'
  get '/contacts', to: 'main#contacts'
  get '/gallery', to: 'main#gallery'
  get '/acryllic', to: 'main#acryllic'
  get '/clamshells', to: 'main#clamshells'
  get '/racks', to: 'main#racks'
  get '/mold', to: 'main#mold'
  get '/moldshell', to: 'main#moldshell'
  get '/blinks', to: 'main#blinks'
  
  resources :products do
     get :who_bought, on: :member
  end

  resources :line_items do
    get  :decrement, on: :member
  end

  #do
    #get '/contacts', as: 'inquiries#index'
  #end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  scope "/:locale" do 
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    resources :subscriptions
    resources :posts
    root 'main#home', as: 'main_home', via: :all
  end 

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

 has_many :line_items, dependent: :destroy

 def add_product(product)
  current_item = line_items.find_by(product_id: product.id)
   if current_item
  	current_item.quantity += 1
   else
  	current_item = line_items.build(product_id: product.id)
   end
    current_item
 end

 def total_price
  line_items.to_a.sum { |item| item.total_price }
 end

 def remove_product(product)     
   current_item = line_items.find_by(product_id: product.id)
   if current_item.quantity > 1 
   	current_item.quantity -=1
   elsif current_item.quantity == 1 
   	current_item.destroy
   end
   	current_item
 end

end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, 
	 length: { minimum: 12, maximum: 255 },
          format: {with: VALID_EMAIL_REGEX }
    validates :message,
          presence: :true      
    mount_uploader :image, ImageUploader  

 end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :order, optional: true 
  belongs_to :product, optional: true
  belongs_to :cart

  def total_price
  	if I18n.locale == :en
  	product.price * quantity 
    else
    product.price_ru * quantity
    end
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
 
 has_many :line_items, dependent: :destroy
 before_save { email.downcase! }
 REGEXP = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

	enum pay_type: {
		"Credit card" => 0,
		"Purchase order" => 1
	}

 validates :name, presence: true, length: { minimum: 3 }
 validates :address, presence: true, length: { minimum: 2, maximum: 150 }
 validates :email, presence: true, length: { minimum: 12, maximum: 255 },
                   format: { with: REGEXP }
                                    
 validates :pay_type, inclusion: pay_types.keys 

    def add_line_items_from_cart(cart)
    	cart.line_items.each do |item|
    		item.cart_id = nil
    		line_items << item
    	end
    end

end

app/models/post.rb
class Post < ApplicationRecord

validates :title, presence: true, length: { minimum: 2, maximum: 150 }
validates :body, presence: true, length: { minimum: 2 }

mount_uploader :image, ImageUploader

end

app/models/product.rb
class Product < ApplicationRecord
	validates :title, :description, :image_url, presence: true
	validates :title, uniqueness: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
	    message: 'Must be a gif, jpg or png image!' }

	has_many :line_items
	has_many :orders, through: :line_items

	before_destroy :ensure_not_referenced_by_any_line_item 
    
   	private

	def ensure_not_referenced_by_any_line_item
	unless line_items.empty?
		errors.add(:base, 'Line Items Present')
		throw :abort
	 end
    end

end

app/models/subscription.rb
class Subscription < ApplicationRecord

 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
 validates :email,
          length: { minimum: 12, maximum: 255 },
          format: {with: VALID_EMAIL_REGEX },
          uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  mount_uploader :image, ImageUploader
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def self.google_map(center)
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=500x500&zoom=17"
    end

  def home
    @subscription = Subscription.new
  end

  def catalog
    @products = Product.all
  end

  def services
  end

  def contacts
    @inquiry = Inquiry.new

  end

  def gallery
    @images = Image.paginate(:page => params[:page], :per_page => 15)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

#before_action :authenticate_admin!, only: [:create, :edit, :update, :destroy]
before_action :set_post, only: [:show, :edit, :update, :destroy]


def index 
 @posts = Post.all
end

def show
  @post = Post.find(params[:id])
end

def new
 @post = Post.new
end

def edit
end

def create 
 @post = Post.new(post_params)
 respond_to do |format|
  if @post.save
 	format.html { redirect_to @post, notice: "Post is created"}
 	format.json { render :show, status: :created, location: @post }
 	SubscriptionMailer.notify(@post).deliver_later
  else
 	format.html { render :new }
 	format.json { render json: @post.errors, status: :unprocessable_entity }
  end
 end
end

def update 
 respond_to do |format| 
  if @post.update(post_params)
  	format.html { redirect_to @post, notice: "Post is updated" }
  	format.json { render :show, status: :ok, location: @post }
  else 
  	format.html { render :edit }
  	format.json { render json: @post.errors, status: :unprocessable_entity }
  end
 end
end

def destroy 
  @post.destroy
   respond_to do |format| 
   format.html { redirect_to posts_url, notice: "Post was destroyed" }
   format.json { head :no_content }
 end
end

private

def post_params
 params.require(:post).permit(:title, :body, :image, :image_cache)
end 



def set_post
@post = Post.find(params[:id])
end



end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = 'Rkraftcomua'
	 if page_title.empty? 
		base_title
	 else
	 	page_title + " | " + base_title
	 end
    end

    def hidden_div_if(condition, attributes = {}, &block)
    	if condition 
    		attributes["style"] = "display:none"
    	end
    	content_tag("div", attributes, &block)
    end

    def gravatar_for(user, size)
     gravatar_id = Digest::MD5.hexdigest(user.email)
     gravatar_url =  "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
     image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |form| %>
 <% if post.errors.any? %>
  <div id="error explanation">
  <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

   <ul> 
   	<% posts.errors.full_messages.each do |message| %>
   	 <li><%= message %></li>
   	<% end %>
   </ul>
  </div>
 <% end %>

<div class="field">
 <%= form.label :title %>
 <%= form.text_field :title, id: :post_title %>
</div>

<div class="field">
 <%= form.label :body %>
 <%= form.text_field :body, id: :post_body %>
</div>

<div>
 <%= form.label :image %>
 <%= form.file_field :image %>
 <%= form.hidden_field :image_cache %>
</div>


<div class="actions">
 <%= form.submit %>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1><%= t('.etitle') %></h1>

<%= render 'form', post: @post %>
<%= link_to t('.show'), @post %>
<%= link_to t('products.show.back'), posts_path %>

app/views/posts/index.html.erb
<div class="center jumbotron">
        <div class="bar background-image-fixed-1 no-mb color-white text-center">
          <div class="dark-mask"></div>
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="icon"><i class="fa fa-file-code-o"></i></div>
                <h1><%= t('.title') %></h1>
                <p class="lead"><%= t('.texts') %></p>
                <p class="text-center"><a href="<%= gallery_path %>" class="btn btn-outline-white-primary"><%= t('.2products') %></a></p>
              </div>
            </div>
          </div>
        </div>
        <!-- *** Blog header with shot end ***-->
        <div class="container">
        </div>
          <!--
         blog first 2 article column appearance
          -->
          
          <div id="blog-homepage" class="row">
            <div class="col-sm-6">
              <div class="post">
                <h4><a href="#"><%= t('.blog1') %></a></h4>
                <p class="author-category">For <a href="#"><%= t('layouts.application.catalog') %></a> in <a href="">Our style</a></p>
                <hr>
                <p class="intro"><%= t('.blog1text') %></p>
                <p class="read-more"><a href="<%= post_path(1) %>" class="btn btn-outline-primary"><%= t('.read') %></a></p>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="post">
                <h4><a href="#"><%= t('.blog2') %></a></h4>
                <p class="author-category">For <a href="<%= clamshells_path %>"><%= t('layouts.application.clamshells') %></a> in <a href="">About Us</a></p>
                <hr>
                <p class="intro"><%= t('.blog2text') %></p>
                <p class="read-more"><a href="<%= post_path(2) %>" class="btn btn-outline-primary"><%= t('.read') %></a></p>
              </div>
            </div>
          </div>


  <!-- end of header parts -->
<h1 class="text-uppercase"><strong><%= t('.tabletitle') %></strong></h1>
<table width="100%" border="0" cellspaceing="0" cellpadding="0">
 <thead style= "background-color: #ced4da">
 <tr class="post_title">
 <th><%= t('.name') %></th>
 <th><%= t('.topic') %></th>
 <th><%= t('.created') %></th>
 <th colspan="4"></th>
</tr>
</thead>
<tbody>
 <!-- blog rest of articles table appearance -->
<% @s = @posts.to_a.sort! %>
<% @s.shift(2) %>
<tr class="post_list">
<% @s.each do |post| %>
<td class="post_title"><%=link_to post.title, post_path(post) %></td>
<td class="post_body"><%= truncate(strip_tags(post.body), length: 100) %></td>
<td class="post_actions"><%= post.created_at %></td>
</td>
</tr>
<% end %>

</tbody>
</table>
</div>
</div>

app/views/posts/new.html.erb
<h1><%= t('.ntitle') %></h1>
<% if !admin_session %>
<p><%= link_to t('show.admin'), new_admin_session_path %></p>
<% end %>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><strong><%= @post.title %></strong></h1>

<p><%= @post.body %></p><br />

<%= image_tag(@post.image.url) if @post.image? %>
<% if !admin_session %>
<p><%= link_to t('.admin'), new_admin_session_path %></p>
<% end %>
<%= link_to t('products.show.back'), posts_path %> |
<%= link_to t('products.show.edit'), edit_post_path(@post) %> |
<%= link_to t('.delete'), @post, method: :delete, data: { confirm: t('.sure') } %>