config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admins' => 'admins#index'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :users
  resources :products
  resources :posts
  resources :subscriptions
  resources :inquiries
  root 'main#home'
  get '/home', to: 'main#home'
  get '/catalog', to: 'main#catalog'
  get 'services', to: 'main#services'
  get '/contacts', to: 'main#contacts'
  get '/gallery', to: 'main#gallery'
  get '/acryllic', to: 'main#acryllic'
  get '/clamshells', to: 'main#clamshells'
  get '/racks', to: 'main#racks'
  get '/mold', to: 'main#mold'
  get '/moldshell', to: 'main#moldshell'
  get '/blinks', to: 'main#blinks'
  
  resources :products do
     get :who_bought, on: :member
  end

  resources :line_items do
    get  :decrement, on: :member
  end

  #do
    #get '/contacts', as: 'inquiries#index'
  #end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  scope "/:locale" do 
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    resources :subscriptions
    resources :posts
    root 'main#home', as: 'main_home', via: :all
  end 

end

app/models/product.rb
class Product < ApplicationRecord
	validates :title, :description, :image_url, presence: true
	validates :title, uniqueness: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
	    message: 'Must be a gif, jpg or png image!' }

	has_many :line_items
	has_many :orders, through: :line_items

	before_destroy :ensure_not_referenced_by_any_line_item 
    
   	private

	def ensure_not_referenced_by_any_line_item
	unless line_items.empty?
		errors.add(:base, 'Line Items Present')
		throw :abort
	 end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   include CurrentCart
  before_action :set_product, only: [:show, :edit, :update, :destroy]
   before_action :set_cart
   before_action :authenticate_admin!, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = Product.order(:title)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
 
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }

       @products = Product.all
       ActionCable.server.broadcast 'products',
       html: render_to_string('products/index', layout: false)
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def who_bought 
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last 
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_index.html.erb
<div class="center jumbotron">
<p id="notice"><%= notice %></p>

<h1><strong><%= t('.title') %></strong></h1>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style="background color: #e0f8f8">

<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even')%>">
   <td> 
    <%= image_tag(product.image_url, class: 'list_image') %>
  </td>


  <% if I18n.locale == :en %>

   <td class="list_description">
     <dl>
       <dt><%= product.title %></dt>
       <dd><%= truncate(strip_tags(product.description), length:80) %></dd>
     </dl>
    </td>
    <td class= "price_line">
      <span class="price"><%= number_to_currency(product.price) %></span>
      <% else %>
     <td class="list_description">
     <dl>
       <dt><%= product.title_ru %></dt>
       <dd><%= truncate(strip_tags(product.description_ru), length:80) %></dd>
     </dl>
    </td>
     <td class= "price_line">
      <span class="price"><%= number_to_currency(product.price_ru) %></span>
      <% end %>
     <%= button_to t('.add_html'), line_items_path(product_id: product) %>
   </td>

    <td class="list actions">
      <%= link_to t('.show'), product %><br/>
      <%= link_to t('.edit'), edit_product_path(product) %><br/>
      <%= link_to t('.delete'), product, method: :delete, data: { confirm: 'Are you sure?'} %>
    </td>
 
  </tr>
  <% end %>
</table>


<%= link_to t('.new'), new_product_path %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path(@products) %>

app/views/products/index.html.erb
<div class="center jumbotron">
<p id="notice"><%= notice %></p>

<h1><strong><%= t('.title') %></strong></h1>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style="background color: #e0f8f8">
<% cache @products do %>
<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even')%>">
   <td> 
    <% cache product  do %> 
    <%= image_tag(product.image_url, class: 'list_image') %>
  </td>
  
  <% if I18n.locale == :en %>

   <td class="list_description">
     <dl>
       <dt><%= product.title %></dt>
       <dd><%= truncate(strip_tags(product.description), length:80) %></dd>
     </dl>
    </td>
    <td class= "price_line">
      <span class="price"><%= number_to_currency(product.price) %></span>
      <% else %>
     <td class="list_description">
     <dl>
       <dt><%= product.title_ru %></dt>
       <dd><%= truncate(strip_tags(product.description_ru), length:80) %></dd>
     </dl>
    </td>
     <td class= "price_line">
      <span class="price"><%= number_to_currency(product.price_ru) %></span>
      <% end %>
    <%= button_to t('.add_html'),
     line_items_path(product_id: product, locale: I18n.locale) %>
  </td>

    <td class="list actions">
      <%= link_to t('.show'), product %><br/>
      <%= link_to t('.edit'), edit_product_path(product) %><br/>
      <%= link_to t('.delete'), product, method: :delete, data: { confirm: 'Are you sure?'} %>
    </td>
 
  </tr>
  <% end %>
  <% end %>
  <% end %>
</table>

<%= link_to t('.new'), new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="center jumbotron">
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('.title') %></strong>
  <% if I18n.locale == :en %>
  <%= @product.title %>
  <% else %>
  <%= @product.title_ru %>
  <% end %>
</p><br />

<p>
  <strong><%= t('.description') %></strong>
  <% if I18n.locale == :en %> 
  <%= @product.description %>
  <% else %>
  <%= @product.description_ru %>
  <% end %>
</p><br />

<p>
  <strong><%= t('.price') %></strong>
  <% if I18n.locale == :en %>
  <%= number_to_currency(@product.price) %>
  <% else %>
  <%= number_to_currency(@product.price_ru) %>
  <% end %>
</p><br />

<p>
  <strong><%= t('.image') %></strong>
  <%= image_tag(@product.image_url) %>
</p><br />

<%= link_to t('.edit'), edit_product_path(@product) %> |
<%= link_to t('.back'), products_path %>