config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admins' => 'admins#index'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :users
  resources :products
  resources :posts
  resources :subscriptions
  resources :inquiries
  root 'main#home'
  get '/home', to: 'main#home'
  get '/catalog', to: 'main#catalog'
  get 'services', to: 'main#services'
  get '/contacts', to: 'main#contacts'
  get '/gallery', to: 'main#gallery'
  get '/acryllic', to: 'main#acryllic'
  get '/clamshells', to: 'main#clamshells'
  get '/racks', to: 'main#racks'
  get '/mold', to: 'main#mold'
  get '/moldshell', to: 'main#moldshell'
  get '/blinks', to: 'main#blinks'
  
  resources :products do
     get :who_bought, on: :member
  end

  resources :line_items do
    get  :decrement, on: :member
  end

  #do
    #get '/contacts', as: 'inquiries#index'
  #end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  scope "/:locale" do 
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    resources :subscriptions
    resources :posts
    root 'main#home', as: 'main_home', via: :all
  end 

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

 has_many :line_items, dependent: :destroy

 def add_product(product)
  current_item = line_items.find_by(product_id: product.id)
   if current_item
  	current_item.quantity += 1
   else
  	current_item = line_items.build(product_id: product.id)
   end
    current_item
 end

 def total_price
  line_items.to_a.sum { |item| item.total_price }
 end

 def remove_product(product)     
   current_item = line_items.find_by(product_id: product.id)
   if current_item.quantity > 1 
   	current_item.quantity -=1
   elsif current_item.quantity == 1 
   	current_item.destroy
   end
   	current_item
 end

end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, 
	 length: { minimum: 12, maximum: 255 },
          format: {with: VALID_EMAIL_REGEX }
    validates :message,
          presence: :true      
    mount_uploader :image, ImageUploader  

 end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :order, optional: true 
  belongs_to :product, optional: true
  belongs_to :cart

  def total_price
  	if I18n.locale == :en
  	product.price * quantity 
    else
    product.price_ru * quantity
    end
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
 
 has_many :line_items, dependent: :destroy
 before_save { email.downcase! }
 REGEXP = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

	enum pay_type: {
		"Credit card" => 0,
		"Purchase order" => 1
	}

 validates :name, presence: true, length: { minimum: 3 }
 validates :address, presence: true, length: { minimum: 2, maximum: 150 }
 validates :email, presence: true, length: { minimum: 12, maximum: 255 },
                   format: { with: REGEXP }
                                    
 validates :pay_type, inclusion: pay_types.keys 

    def add_line_items_from_cart(cart)
    	cart.line_items.each do |item|
    		item.cart_id = nil
    		line_items << item
    	end
    end

end

app/models/post.rb
class Post < ApplicationRecord

validates :title, presence: true, length: { minimum: 2, maximum: 150 }
validates :body, presence: true, length: { minimum: 2 }

mount_uploader :image, ImageUploader

end

app/models/product.rb
class Product < ApplicationRecord
	validates :title, :description, :image_url, presence: true
	validates :title, uniqueness: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
	    message: 'Must be a gif, jpg or png image!' }

	has_many :line_items
	has_many :orders, through: :line_items

	before_destroy :ensure_not_referenced_by_any_line_item 
    
   	private

	def ensure_not_referenced_by_any_line_item
	unless line_items.empty?
		errors.add(:base, 'Line Items Present')
		throw :abort
	 end
    end

end

app/models/subscription.rb
class Subscription < ApplicationRecord

 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
 validates :email,
          length: { minimum: 12, maximum: 255 },
          format: {with: VALID_EMAIL_REGEX },
          uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  mount_uploader :image, ImageUploader
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admins/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

<%= render partial: 'inquiries/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 

      <%= stylesheet_link_tag 'carousel.css', media: 'print, screen' %>
  <%= javascript_include_tag('jquery.js') %>
  <%= javascript_include_tag('jquery.min.js') %>
  <%= javascript_include_tag('bootstrap.js') %>
  <%= javascript_include_tag('carousel.js') %>
  <%= javascript_include_tag('jquery_ujs.js') %>

    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="">
  
    <!-- Google fonts - Montserrat and Merriweather-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Merriweather:400,400italic" rel="stylesheet" type="text/css">
  </head>
 <!-- Font Awesome css-->
  <body>
    <header>


   <!-- *** NAVBAR *** -->
    <nav class="navbar navbar-light fixed-top navbar-expand-lg yamm justify-content-between">

                  <div class="container"><a href="<%= home_path %>" class="navbar-brand home"><img src="<%= asset_path 'logo_rkraft.jpg' %>" alt="Rkraft logo" class="d-none d-md-inline-block"><span class="sr-only">Rkraftcomua - homepage</span></a>

     
          <div class="navbar-nav mr-auto">
            <div class="nav-item active dropdown normal-dropdown"><a id="homeDropdown" href="<%= home_path %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Home</a>
              <div aria-labelledby="homeDropdown" class="dropdown-menu"><a href="<%= home_path %>" class="dropdown-item">Home - default</a><a href="<%= catalog_path %>" class="dropdown-item">Home - intro image</a><a img src="<%= asset_path 'title.png' %>" class="dropdown-item">Home - fullscreen slider <span class="badge badge-success">New</span></a></div>
            </div>
            <div class="nav-item dropdown yamm-fw"><a href="<%= 'clamshells' %>" data-toggle="dropdown" class="nav-link dropdown-toggle"><%= t('.menu') %><b class="caret"></b></a>
              <div class="dropdown-menu">
                <div class="yamm-content">
                  <div class="row">
                    <div class="col-lg-3 d-none d-lg-inline-block"><img src="<%= asset_path 'disacr.jpg' %>" alt="" class="img-fluid"></div>
                    <div class="col-sm-4 col-lg-3">
                      <h3><%= t('.catalog') %></h3>
                      <ul>
                        <li><a href="<%= acryllic_path %>"><%= t('.acryllic') %></a></li>
                        <li><a href="<%= racks_path %>"><%= t('.metal') %></a></li>
                        <li><a href="<%= mold_path %>"><%= t('.mold') %></a></li>
                        <li><a href="<%= clamshells_path %>"><%= t('.clamshells') %></a></li>
                      </ul>
                    </div>
                    <div class="col-sm-4 col-lg-3">
                      <h3><%= t('.additional') %></h3>
                      <ul>
                        <li><a href="<%= moldshell_path %>"><%= t('.moldshell') %></a></li>
                        <li><a href="<%= blinks_path %>"><%= t('.lighting') %></a></li>
                        <li><a href="<%= moldshell_path %>"><%= t('.shelftalkers') %></a></li>
                        <li><a href="#"><%= t('.accessories') %></a></li>
                      </ul>
                    </div>
                    <div class="col-sm-4 col-lg-3">
                      <h3><%= t('.services') %></h3>
                      <ul>
                        <li><a href="#"><%= t('.design') %></a></li>
                        <li><a href="#"><%= t('.constructing') %></a></li>
                        <li><a href="#"><%= t('.3dmodelling') %></a></li>
                        <li><a href="#"><%= t('.consulting') %></a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                 <div class="footer clearfix d-none d-lg-block">
                  <h4 class="pull-right"><%= t('.acryllic') %></h4>
                  <div class="buttons pull-left"><a href="<%= acryllic_path %>" class="btn btn-light btn-sm mr-2"><i class="fa fa-tags"></i><%= t('.sales') %></a><a href="<%= catalog_path %>" class="btn btn-light btn-sm mr-2"><i class="fa fa-star-o"></i><%= t('.favorites') %></a><a href="<%= products_path %>" class="btn btn-light btn-sm mr-2"><i class="fa fa-globe"></i><%= t('.inquiry') %></a></div>
                </div>
              </div>
            </div>
            <div class="nav-item dropdown yamm-fw"><a href="<%= catalog_path %>" data-toggle="dropdown" class="nav-link dropdown-toggle"><%= t('.prods') %><b class="caret"></b></a>
              <div class="dropdown-menu">
                <div class="yamm-content">
                  <div class="row">
                    <div class="col-lg-3 d-none d-lg-inline-block"><img src="<%= asset_path 'shelf11.png' %>" alt="" class="img-fluid"></div>
                    <div class="col-sm-4 col-lg-3">
                      <h3><%= t('.catalog') %></h3>
                      <ul>
                        <li><a href="<%= gallery_path %>"><%= t('.gallery') %></a></li>
                        <li><a href="<%= catalog_path %>"><%= t('.catalog') %></a></li>
                        <li><a href="<%= products_path %>"><%= t('.products') %></a></li>
                        <li><a href="<%= products_path %>"><%= t('.prodetail') %></a></li>
                      </ul>
                    </div>
                    <div class="col-sm-4 col-lg-3">
                      <h3><%= t('.contacts') %></h3>
                      <ul>
                        <li><a href="<%= contacts_path %>"><%= t('main.contacts.inqform') %></a></li>
                        <li><a href="<%= contacts_path %>"><%= t('main.contacts.social') %></a></li>
                        <li><a href="<%= contacts_path %>"><%= t('main.contacts.map') %></a></li>
                        <li><a href="<%= home_path %>"><%= t('main.home.subscription') %></a></li>
                      </ul>
                    </div>
                    <div class="col-sm-4 col-lg-3">
                     <h3><%= t('.services') %></h3>
                      <ul>
                        <li><a href="<%= services_path %>"><%= t('.design') %></a></li>
                        <li><a href="<%= services_path %>"><%= t('.constructing') %></a></li>
                        <li><a href="<%= services_path %>"><%= t('.3dmodelling') %></a></li>
                        <li><a href="<%= services_path %>"><%= t('.consulting') %></a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="footer clearfix d-none d-lg-block">
                  <h4 class="pull-right"><%= t('.shelftalkers') %></h4>
                  <div class="buttons pull-left"><a href="<%= mold_path %>" class="btn btn-light btn-sm mr-2"><i class="fa fa-tags"></i><%= t('.sales') %></a><a href="<%= catalog_path %>" class="btn btn-light btn-sm mr-2"><i class="fa fa-star-o"></i><%= t('.favorites') %></a><a href="<%= products_path %>" class="btn btn-light btn-sm mr-2"><i class="fa fa-globe"></i><%= t('.inquiry') %></a></div>
                </div>
              </div>
            </div>
            <div class="nav-item dropdown yamm-fw"><a href="<%= gallery_path %>" data-toggle="dropdown" data-hover="dropdown" class="nav-link dropdown-toggle"><%= t('.shop') %><b class="caret"></b></a>
              <div class="dropdown-menu">
                <div class="yamm-content">
                  <div class="row">
                    <div class="col-sm-6 col-lg-3">
                      <h5>Homepage</h5>
                      <ul>
                        <li><a href="<%= home_path %>">Homepage - with slideshow</a></li>
                        <li><a href="#">Homepage - with intro image</a></li>
                        <li><a href="#">Homepage - fullscreen slider <span class="badge badge-success">New</span></a></li>
                      </ul>
                      <h5><%= t('.shops') %></h5>
                      <ul>
                        <li><a href="<%= gallery_path %>"><%= t('.gallery') %></a></li>
                        <li><a href="<%= catalog_path %>"><%= t('.catalog') %></a></li>
                        <li><a href="<%= products_path %>"><%= t('.products') %></a></li>
                        <li><a href="<%= products_path %>"><%= t('.prodetail') %></a></li>
                      </ul>
                    </div>
                 
                    <div class="col-sm-6 col-lg-3" id="cart">
                      <h5><%= t('.order_process') %></h5>
                      <ul>
                        <li><a href="<%= catalog_path %>"><%= t('.sh_cart') %></a></li>
                        <li><a href="<%= new_order_path %>"><%= t('.checkout') %></a></li>
                      </ul>
                    </div>
                    <div class="col-sm-6 col-lg-3">
                      <h5><%= t('.blog') %></h5>
                      <ul>
                        <li><a href="<%= posts_path %>"><%= t('.articles') %></a></li>
                        <li><a href="<%= new_post_path %>"><%= t('.post') %></a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">About <span class="badge badge-success">New</span></a></li>
                        <li><a href="<%= contacts_path %>"><%= t('.contacts') %></a></li>
                      </ul>
                    </div>
                  </div>
                </div>
                <!-- /.yamm-content-->
              
              </div>
            </div>

            <div class="nav-item"><a href="<%= contacts_path %>" class="nav-link"><%= t('.contacts') %></a></div>
          </div>
        
         <div class="nav-item dropdown yamm-fw"><a href="<%= gallery_path %>" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="nav-link dropdown-toggle"><%= t('.userarea') %><b class="caret"></b></a>
              <div class="dropdown-menu">
                <div class="yamm-content">
                  <div class="row">
                    <div class="col-sm-6 col-lg-3">

        <% if !user_signed_in? %>
                              <h5>Registrations</h5>
                      <ul>
        <li><%= link_to t('.sign_up'), new_user_registration_path %></li>
        <li><%= link_to t('.log_in'), new_user_session_path %></li>
                      </ul>
                    </div>
                      <div class="col-sm-6 col-lg-3" id="cart">
                      <% else %>
                        <h5>Edit Profile</h5>
                      <ul>  
                      
                      <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li> 
                      </ul>  
                      <% end %>                  
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
  
      </nav>
     </div>
        <!-- /.nav-collapse-->
      </div>
    </nav>
    <!-- /#navbar-->
    <!-- *** NAVBAR END ***-->



  
  <% if @cart %>
  <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
  <%= render @cart %>
  <% end %>
  <% end %>

  <% if flash[:success] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:success] %>
    </div>
  <% end %>

        <% if session[:user_id] %>
       <ul>
         <li><%= link_to 'Orders', orders_path %></li>
         <li><%= link_to 'Products', products_path %></li>
         <li><%= link_to 'Users', users_path %></li>
       </ul>
       <%= button_to 'Logout',  destroy_user_session %>
      <% end %>

  </header>


  <div class="container">
    <footer class='<% controller.controller_name %>'>
    <%= yield %>
  </div>


<div class=container>
<div class="col-lg-3 col-md-6">
              <h4><%= t('.where') %></h4>
              <p><strong>Maps</strong><br>Ukraine<br>   Kyiv Region <br>    Find on map<br>   Kyiv <br><strong><%= t('.contacts') %></strong></p><a href="<%= contacts_path %>"><%= t('.gocontacts') %></a>
              <hr class="d-block d-md-none">
            </div>
            <!-- /.col-lg-3-->
            
        
            
                            <!-- /input-group-->
            
              <hr>
              <h4>Stay in touch</h4>
              <p class="social"><a href="https://www.facebook.com/RkraftManufacturing/"><i class="fa fa-facebook-square"></i></a><a href="#"><i class="fa fa-instagram"></i></a><a href="#"><i class="fa fa-google-plus"></i></a><a href="#"><i class="fa fa-envelope"></i></a></p>
            </div>
            <!-- /.col-lg-3-->
          </div>
          <!-- /.row-->
        </div>
        <!-- /.container-->
     

 <!-- *** FOOTER END ***-->

</div>

</footer>
</body>

</html>